language: node_js
node_js:
  - "6"
brancher:
  only:
    - "dev"
    - "master"
install:
  - "yarn add"
  - "yarn add -g codecov"
script:
  - "yarn run cover",
  - codecov
after_success:
- bash <(curl -s https://codecov.io/bash)
